# Waves configuration.

maethstro:
  port: 8100
  host: 0.0.0.0
  liquid:
    host: localhost
    port: 8101
    osc_port: 7777
    mount: /waves
    password: 9mRTjfIRvh+4gEwakEl1bw
  tracks:
  - name: bass
    instrument:
      path: data/salamandar.vst3
      preset: presets/salamander-bass.vstpreset
    effects:
    - path: data/mauve.vst3
      preset: presets/mauve.vstpreset
