[tool.poetry]
name = "soir"
version = "0.9.0"
description = "Live Coding Environment"
authors = ["s. rannou <mxs@sbrk.org>"]
license = "MIT"
packages = [
         { include = "soir", from = "py" },
]

[tool.poetry.dependencies]
python = "3.11.11"
mkdocs = "^1.6.0"
mkdocstrings = {extras = ["python"], version = "^0.25.1"}
mkdocs-material = "^9.5.21"
mkdocs-autorefs = "^1.0.1"
typer = "^0.12.3"
pyyaml = "^6.0.2"
regex = "^2024.11.6"
jinja2 = "^3.1.4"
prettytable = "^3.12.0"
black = "^25.1.0"
rich = "^14.0.0"
textual = "^3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
