#include "vst/vst_scanner.hh"

#include <absl/log/log.h>

#include <filesystem>
#include <fstream>

#ifdef __linux__
#include <dlfcn.h>
#endif

#include <nlohmann/json.hpp>

#include "pluginterfaces/vst/ivstaudioprocessor.h"
#include "public.sdk/source/vst/hosting/module.h"

namespace soir {
namespace vst {

namespace fs = std::filesystem;

VstScanner::VstScanner() : search_paths_(GetDefaultSearchPaths()) {}

std::vector<std::string> VstScanner::GetDefaultSearchPaths() {
  std::vector<std::string> paths;

#if defined(__APPLE__)
  paths.push_back("/Library/Audio/Plug-Ins/VST3");

  const char* home = std::getenv("HOME");
  if (home) {
    paths.push_back(std::string(home) + "/Library/Audio/Plug-Ins/VST3");
  }
#elif defined(_WIN32)
  paths.push_back("C:\\Program Files\\Common Files\\VST3");
  paths.push_back("C:\\Program Files (x86)\\Common Files\\VST3");
#elif defined(__linux__)
  paths.push_back("/usr/lib/vst3");
  paths.push_back("/usr/local/lib/vst3");

  const char* home = std::getenv("HOME");
  if (home) {
    paths.push_back(std::string(home) + "/.vst3");
  }
#endif

  return paths;
}

void VstScanner::AddSearchPath(const std::string& path) {
  search_paths_.push_back(path);
}

absl::Status VstScanner::Scan(std::map<std::string, PluginInfo>* plugins) {
  for (const auto& path : search_paths_) {
    auto status = ScanDirectory(path, plugins);
    if (!status.ok()) {
      LOG(WARNING) << "Failed to scan directory " << path << ": " << status;
    }
  }

  return absl::OkStatus();
}

absl::Status VstScanner::ScanDirectory(
    const std::string& path, std::map<std::string, PluginInfo>* plugins) {
  if (!fs::exists(path)) {
    return absl::OkStatus();
  }

  for (const auto& entry : fs::recursive_directory_iterator(path)) {
    if (entry.is_directory() && entry.path().extension() == ".vst3") {
      auto status = ProbePlugin(entry.path().string(), plugins);
      if (!status.ok()) {
        LOG(WARNING) << "Failed to probe plugin " << entry.path() << ": "
                     << status;
      }
    }
  }

  return absl::OkStatus();
}

absl::Status VstScanner::ProbePlugin(
    const std::string& bundle_path,
    std::map<std::string, PluginInfo>* plugins) {
  // Prefer moduleinfo.json (VST3 SDK 3.7+, generated by yabridge 5.x for
  // bridged plugins). Reading the JSON skips loading the plugin library
  // entirely, avoiding any transient Wine host processes during scanning.
  auto json_path =
      fs::path(bundle_path) / "Contents" / "Resources" / "moduleinfo.json";
  std::ifstream f(json_path);
  if (f.is_open()) {
    auto doc = nlohmann::json::parse(f, nullptr, false);
    if (!doc.is_discarded() && doc.contains("Classes")) {
      for (const auto& cls : doc["Classes"]) {
        if (!cls.contains("Category") ||
            cls["Category"].get<std::string>() != "Audio Module Class") {
          continue;
        }

        PluginInfo info;
        info.path = bundle_path;

        if (cls.contains("CID")) info.uid = cls["CID"].get<std::string>();
        if (cls.contains("Name")) info.name = cls["Name"].get<std::string>();
        if (cls.contains("Vendor"))
          info.vendor = cls["Vendor"].get<std::string>();

        bool is_instrument = false;
        if (cls.contains("Sub Categories")) {
          std::string categories;
          for (size_t i = 0; i < cls["Sub Categories"].size(); ++i) {
            if (i > 0) categories += "|";
            std::string cat = cls["Sub Categories"][i].get<std::string>();
            categories += cat;
            if (cat == "Instrument") is_instrument = true;
          }
          info.category = categories;
        }

        info.num_audio_inputs = is_instrument ? 0 : 2;
        info.num_audio_outputs = 2;
        info.type = is_instrument ? VstPluginType::kVstInstrument
                                  : VstPluginType::kVstFx;

        if (!info.name.empty()) {
          (*plugins)[info.name] = info;
          LOG(INFO) << "Found VST " << (is_instrument ? "instrument" : "effect")
                    << ": " << info.name << " (" << info.vendor << ")";
        }
      }
      return absl::OkStatus();
    }
  }

  // Fall back to loading the module for plugins without moduleinfo.json.
  std::string error;
  std::shared_ptr<VST3::Hosting::Module> module =
      VST3::Hosting::Module::create(bundle_path, error);
  if (!module) {
    return absl::InternalError("Failed to load module: " + error);
  }

  auto factory = module->getFactory();
  if (!factory.get()) {
    return absl::InternalError("Failed to get factory");
  }

#ifdef __linux__
  // Pin the plugin .so against unload so that ModuleExit is not called while
  // background threads (e.g. JUCE message thread) may still be running.
  for (auto& ci : factory.classInfos()) {
    if (ci.category() == kVstAudioEffectClass) {
      auto comp = factory.createInstance<Steinberg::Vst::IComponent>(ci.ID());
      if (comp) {
        void* vtable = *reinterpret_cast<void**>(comp.get());
        ::Dl_info dl_info{};
        if (::dladdr(vtable, &dl_info) && dl_info.dli_fname) {
          ::dlopen(dl_info.dli_fname, RTLD_NOLOAD | RTLD_NODELETE | RTLD_LAZY);
        }
      }
      break;
    }
  }
#endif

  for (auto& info : factory.classInfos()) {
    if (info.category() == kVstAudioEffectClass) {
      PluginInfo plugin_info;

      plugin_info.uid = info.ID().toString();
      plugin_info.name = info.name();
      plugin_info.vendor = info.vendor();

      auto subcats = info.subCategories();
      std::string categories;
      bool is_instrument = false;
      for (size_t i = 0; i < subcats.size(); ++i) {
        if (i > 0) categories += "|";
        categories += subcats[i];
        if (subcats[i] == "Instrument") is_instrument = true;
      }
      plugin_info.category = categories;
      plugin_info.path = bundle_path;
      plugin_info.num_audio_inputs = is_instrument ? 0 : 2;
      plugin_info.num_audio_outputs = 2;
      plugin_info.type =
          is_instrument ? VstPluginType::kVstInstrument : VstPluginType::kVstFx;

      (*plugins)[plugin_info.name] = plugin_info;
      LOG(INFO) << "Found VST " << (is_instrument ? "instrument" : "effect")
                << ": " << plugin_info.name << " (" << plugin_info.vendor
                << ")";
    }
  }

  return absl::OkStatus();
}

}  // namespace vst
}  // namespace soir
